name: mvvm_generator
description: Dart CLI tool to generate Flutter MVVM structure (View, Cubit, Model, Repository, and API).
homepage: https://github.com/mohamedzebib22/mvvm_generator
repository: https://github.com/mohamedzebib22/mvvm_generator
version: 1.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <4.0.0"
executables:
  mvvm_page:
  mvvm_core_api:
  mvvm_page_repo:
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
